services:
  - type: web
    name: e-library-management-system
    runtime: node
    buildCommand: npm install --prefix back && npm install --include=dev --prefix front && npm run build --prefix front
    startCommand: node back/server.js
    envVars:
      - key: NODE_ENV
        value: production
